[package]
name = "cofferdam-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Cofferdam command-line binary."

[[bin]]
name = "cofferdam"
path = "src/main.rs"

[[test]]
name = "fix"
path = "tests/fix.rs"

[dependencies]
cofferdam-core = { workspace = true }
cofferdam-ts = { workspace = true }
cofferdam-engine = { workspace = true }
cofferdam-checks = { workspace = true }
cofferdam-formatters = { workspace = true }
clap = { workspace = true }
clap-markdown = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = "3"
toml = { workspace = true }
