// AUTOGENERATED by `cofferdam gen-docs` — do not edit.
// Source of truth: every entry in `cofferdam_checks::all_builtins()`.
// Adding a new check? Add it to `all_builtins()`, write its companion
// file at `crates/cofferdam-checks/docs/<id>.md`, then run `cofferdam gen-docs`.
//
// Imported by `config.ts` as the Built-in checks sidebar group.

export const checksItems = [
  { text: 'All checks', link: '/checks/' },
  {
    text: 'Consistency',
    collapsed: true,
    items: [
      { text: 'BroadSuppression', link: '/checks/Consistency.BroadSuppression' },
      { text: 'QuoteStyle', link: '/checks/Consistency.QuoteStyle' },
      { text: 'UnusedSuppression', link: '/checks/Consistency.UnusedSuppression' },
    ],
  },
  {
    text: 'Design',
    collapsed: true,
    items: [
      { text: 'BoundaryFrozen', link: '/checks/Design.BoundaryFrozen' },
      { text: 'DuplicateExportName', link: '/checks/Design.DuplicateExportName' },
      { text: 'ImportCycle', link: '/checks/Design.ImportCycle' },
      { text: 'InvariantViolation', link: '/checks/Design.InvariantViolation' },
      { text: 'LayerViolation', link: '/checks/Design.LayerViolation' },
      { text: 'MaxParameters', link: '/checks/Design.MaxParameters' },
      { text: 'OrphanExport', link: '/checks/Design.OrphanExport' },
      { text: 'ScriptedInvariant', link: '/checks/Design.ScriptedInvariant' },
      { text: 'UnionExhaustivenessGap', link: '/checks/Design.UnionExhaustivenessGap' },
      { text: 'MissingPubDoc', link: '/checks/Rust.MissingPubDoc' },
    ],
  },
  {
    text: 'Readability',
    collapsed: true,
    items: [
      { text: 'MaxFunctionLength', link: '/checks/Readability.MaxFunctionLength' },
      { text: 'MaxLineLength', link: '/checks/Readability.MaxLineLength' },
    ],
  },
  {
    text: 'Refactor',
    collapsed: true,
    items: [
      { text: 'CognitiveComplexity', link: '/checks/Refactor.CognitiveComplexity' },
      { text: 'CyclomaticComplexity', link: '/checks/Refactor.CyclomaticComplexity' },
      { text: 'DeadExport', link: '/checks/Refactor.DeadExport' },
      { text: 'DuplicateBlock', link: '/checks/Refactor.DuplicateBlock' },
      { text: 'LongAndComplex', link: '/checks/Refactor.LongAndComplex' },
      { text: 'MutatedParameter', link: '/checks/Refactor.MutatedParameter' },
      { text: 'PreferArrayMethodOverLoop', link: '/checks/Refactor.PreferArrayMethodOverLoop' },
      { text: 'PreferConstOverLet', link: '/checks/Refactor.PreferConstOverLet' },
      { text: 'PreferNullishCoalescing', link: '/checks/Refactor.PreferNullishCoalescing' },
      { text: 'PreferOptionalChain', link: '/checks/Refactor.PreferOptionalChain' },
      { text: 'UnusedVariable', link: '/checks/Refactor.UnusedVariable' },
    ],
  },
  {
    text: 'Warning',
    collapsed: true,
    items: [
      { text: 'MissingLangAttribute', link: '/checks/Html.MissingLangAttribute' },
      { text: 'NoUnimplementedInNonTest', link: '/checks/Rust.NoUnimplementedInNonTest' },
      { text: 'NoUnwrapInLib', link: '/checks/Rust.NoUnwrapInLib' },
      { text: 'NoConsoleLog', link: '/checks/Warning.NoConsoleLog' },
      { text: 'NoDebugger', link: '/checks/Warning.NoDebugger' },
      { text: 'NoEval', link: '/checks/Warning.NoEval' },
      { text: 'TripleEquals', link: '/checks/Warning.TripleEquals' },
      { text: 'UnusedImport', link: '/checks/Warning.UnusedImport' },
      { text: 'UnusedNullCheck', link: '/checks/Warning.UnusedNullCheck' },
    ],
  },
]
