// AUTOGENERATED by `cofferdam gen-docs` — do not edit.
// Source of truth: every entry in `cofferdam_checks::all_builtins()`.
// Adding a new check? Add it to `all_builtins()`, write its companion
// file at `crates/cofferdam-checks/docs/<id>.md`, then run `cofferdam gen-docs`.
//
// Imported by `config.ts` as the Built-in checks sidebar group.

export const checksItems = [
  { text: 'All checks', link: '/checks/' },
  {
    text: 'Consistency',
    collapsed: true,
    items: [
      { text: 'BroadSuppression', link: '/checks/Consistency.BroadSuppression' },
      { text: 'ErrorHandlingIdiom', link: '/checks/Consistency.ErrorHandlingIdiom' },
      { text: 'UnusedSuppression', link: '/checks/Consistency.UnusedSuppression' },
    ],
  },
  {
    text: 'Design',
    collapsed: true,
    items: [
      { text: 'BarrelReexportBloat', link: '/checks/Design.BarrelReexportBloat' },
      { text: 'BoundaryFrozen', link: '/checks/Design.BoundaryFrozen' },
      { text: 'ClassAsDataBag', link: '/checks/Design.ClassAsDataBag' },
      { text: 'DuplicateExportName', link: '/checks/Design.DuplicateExportName' },
      { text: 'DuplicateTypeShape', link: '/checks/Design.DuplicateTypeShape' },
      { text: 'EffectLeakage', link: '/checks/Design.EffectLeakage' },
      { text: 'ImportCycle', link: '/checks/Design.ImportCycle' },
      { text: 'ImportFanOutOutlier', link: '/checks/Design.ImportFanOutOutlier' },
      { text: 'InvariantViolation', link: '/checks/Design.InvariantViolation' },
      { text: 'LayerViolation', link: '/checks/Design.LayerViolation' },
      { text: 'MissingTestFile', link: '/checks/Design.MissingTestFile' },
      { text: 'OrphanExport', link: '/checks/Design.OrphanExport' },
      { text: 'ReadonlyArrayParam', link: '/checks/Design.ReadonlyArrayParam' },
      { text: 'ScriptedInvariant', link: '/checks/Design.ScriptedInvariant' },
      { text: 'UnionExhaustivenessGap', link: '/checks/Design.UnionExhaustivenessGap' },
      { text: 'MissingPubDoc', link: '/checks/Rust.MissingPubDoc' },
    ],
  },
  {
    text: 'Refactor',
    collapsed: true,
    items: [
      { text: 'DeadExport', link: '/checks/Refactor.DeadExport' },
      { text: 'LongAndComplex', link: '/checks/Refactor.LongAndComplex' },
      { text: 'MixedThrowAndReturnError', link: '/checks/Refactor.MixedThrowAndReturnError' },
      { text: 'NearDuplicateBlock', link: '/checks/Refactor.NearDuplicateBlock' },
      { text: 'PurityHeuristic', link: '/checks/Refactor.PurityHeuristic' },
      { text: 'SideEffectInMapCallback', link: '/checks/Refactor.SideEffectInMapCallback' },
    ],
  },
  {
    text: 'Warning',
    collapsed: true,
    items: [
      { text: 'MissingLangAttribute', link: '/checks/Html.MissingLangAttribute' },
      { text: 'NoUnimplementedInNonTest', link: '/checks/Rust.NoUnimplementedInNonTest' },
      { text: 'NoUnwrapInLib', link: '/checks/Rust.NoUnwrapInLib' },
    ],
  },
]
